"""delete posts cascade

Revision ID: 28ced816a423
Revises: e84a82b1f90b
Create Date: 2022-08-11 13:53:15.297316

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "28ced816a423"
down_revision = "e84a82b1f90b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
