"""delete posts cascade

Revision ID: e84a82b1f90b
Revises: 9338a9bec1e1
Create Date: 2022-08-11 13:50:18.094223

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e84a82b1f90b"
down_revision = "9338a9bec1e1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
